### PR TITLE
Upgrade to Django 1.8

### LINKED ISSUE #57: Upgrade to Django 1.8
Update the app code and tests for Django 1.8

### PR DESCRIPTION
**Pull request by damonkelley**
Resolves #57

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @ldko @somexpert

**Comment by somexpert** [comment]
:thumbsup:

**Comment by ldko** [comment]
:+1:  admin media changes to come in separate PR

**Comment by damonkelley** [comment]
>admin media changes to come in separate PR

Yes. See #59 for those changes.

**Pull request merged**
