### PR TITLE
Display all nodes on one page for APP feed.

### PR DESCRIPTION
**Pull request by ldko**
We want to display all node entries at `/APP/node` on one page.

@vphill is this kind of what you are thinking?

### CODE REVIEW

**Comment by vphill** [comment]
:+1:

**Comment by ldko** [comment]
@somexpert @damonkelley here is a one line change for review.

**Comment by somexpert** [comment]
:thumbsup:

**Comment by damonkelley** [comment]
As mentioned in Slack, we can reduce this to one query with something like the following.

```python
nodes = Node.objects.all()
paginator = Paginator(nodes, len(nodes))
# ...
```

**Comment by damonkelley** [comment]
:+1:

**Pull request merged**
