### PR TITLE
Tests for AtomNextNewsFeed.

### PR DESCRIPTION
**Pull request by damonkelley**
Partially resolves issue #7

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @ldko @somexpert

**Comment by damonkelley** [comment]
Once this and #45 are merged the validate app will have sufficient test coverage.

**Comment by somexpert** [comment]
While I'm not a big fan of testing the reason string but not the object being returned, I can totally see why you would do that. Plus, the feed code is flagelous (as we discussed before), so :thumbsup:

**Comment by damonkelley** [comment]
>While I'm not a big fan of testing the reason string but not the object being returned, I can totally see why you would do that.

I am right there with you.

**Comment by ldko** [comment]
:+1:

**Pull request merged**
