### PR TITLE
Dj 11

### PR DESCRIPTION
**Pull request by madhulika95b**
@ldko @somexpert  Upgraded coda to django 1.11. Please review the changes.

### CODE REVIEW

**Comment by somexpert** [comment]
oh, right, with DEBUG set to True it should work fine with an empty ALLOWED_HOSTS in the local settings. But still, that's something we do want generally in the secrets template

**Comment by madhulika95b** [comment]
I don't think ALLOWED_HOSTS is required in secrets.json file as it isn't required for the application to run but just for tests which have the setting `HTTP_HOST="example.com"`.

**Comment by somexpert** [comment]
It may not be required when running things through docker, but if you were actually going to do a production deployment, the production settings do expect to retrieve the allowed hosts through the settings files. I _think_ we need to put it in the template, and then it will simply be left empty most of the time, but I could be misunderstanding things.

**Comment by somexpert** [comment]
This is something we can deal with later in #132

**Comment by ldko** [comment]
Do we need to run `makemigrations` since there was a minor change to models in one of the Django version upgrades?

**Comment by madhulika95b** [comment]
Yes! I think I'll have to do that

**Comment by ldko** [comment]
Ah, saw your Edit on the comment. No, we don't need to add that to the README. I realize now the likely reason it showed there were migrations to be created when I deployed this in Docker was because the requirements.txt was still using master of django-premis-event-service which didn't have the migration in it. When it uses the django 1.11 version, it will have it.

**Pull request merged**
