### PR TITLE
Replication Utilities Tests

### PR DESCRIPTION
**Pull request by damonkelley**
Will partially complete issue #7 

Notes the function `queue_object_to_xml` does not have tests because it is never used.

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @ldko @somexpert

**Comment by ldko** [comment]
:+1: (but that position vs. queue_position is sad)

**Comment by somexpert** [comment]
:thumbsup:

**Comment by damonkelley** [comment]
@ldko at least it is a super easy fix. (#39)

**Pull request merged**
