### PR TITLE
Smallfixes

### PR DESCRIPTION
**Pull request by runderwood**
@ldko @somexpert refs. #68, #86, and #92

### CODE REVIEW

**Comment by ldko** [comment]
Regarding updating [template settings to 1.8](https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/), I think we could further comply by:
* Replacing `django.core.context_processors` with `django.template.context_processors` in the names of the context processors
* Remove `TEMPLATE_DEBUG` setting since it is same as DEBUG

**Comment by runderwood** [comment]
Removed references to `TEMPLATE_DEBUG` and `django.core.context_processors`. Replaced the latter w/ `django.template.context_processors` in 97f50b0.

**Comment by somexpert** [comment]
Looks good to me! :thumbsup:

**Comment by ldko** [comment]
me too :+1:

**Pull request merged**
